- name: "install dependence packages"
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - openssl-devel
    - bzip2-devel
    - libxslt-devel
    - sqlite-devel

- name: "wget python package"
  get_url: url={{ python_src_url }} dest=/var/tmp

- name: "expand python"
  command: tar xzvf Python-{{ python_version }}.tgz chdir=/var/tmp

- name: "install Python"
  shell: >-
    ./configure --prefix={{ python_prefix }} &&
    make &&
    make install chdir=/var/tmp/Python-{{ python_version }}
