- name: "install dependence packages"
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - openssl-devel
    - bzip2-devel
    - libxslt-devel
    - sqlite-devel

- name: "wget python package"
  get_url: url={{ python_src_url }} dest=/tmp

- name: "expand python"
  command: tar xzvf Python-{{ python_version }}.tgz chdir=/tmp

- name: "install Python"
  shell: >-
    ./configure --prefix={{ python_prefix }} &&
    make &&
    make install chdir=/tmp/Python-{{ python_version }}

- name: "create symlink"
  file: src={{ python_prefix }} dest={{ python_symlink }} state=link

- name: "add ldconfig"
  shell: echo "{{ python_symlink }}/lib" > /etc/ld.so.conf.d/python.conf && ldconfig

- name: "install pip"
  shell: "curl -L {{ python_get_pip_url }} | {{python_prefix}}/bin/python"

- name: "install virtualenv"
  shell: "{{python_prefix}}/bin/pip install virtualenv"
